### ISSUE TITLE
Add Sparsepp to benchmarks

### ISSUE THREAD

**Issue by Leandros** [Tessil/sparse-map#1]
Would be great if this could be compared to: https://github.com/greg7mdp/sparsepp/
It's based on Google's dense map, but should do a little better.

**Comment by Tessil** [comment]
You probably went through the [benchmark's](https://tessil.github.io/2016/08/29/benchmark-hopscotch-map.htm) introduction a bit too fast. You can find an extra [link](https://tessil.github.io//other/hash_table_benchmark.html) with more hash maps including `spp::sparse_hash_map`.

**Comment by Leandros** [comment]
Ooops, missed that! Awesome! Thanks.
