### ISSUE TITLE
conan package

### ISSUE THREAD

**Issue by bigerl** [Tessil/sparse-map#10]
Do you have any plans to make a conan package for this project?
I think it is as great as your other projects you publish as conan packages already. ;)

**Comment by Tessil** [comment]
Hi,

I added the conan package, check [tsl-sparse-map](https://bintray.com/tessil/tsl/tsl-sparse-map%3Atessil). I will submit it later to the conan-center.

Please let me know if there is any problem,
Thibaut

**Comment by bigerl** [comment]
works like a charm. thank you!
