### ISSUE TITLE
[feature request] Support for serialization

### ISSUE THREAD

**Issue by rob-p** [Tessil/sparse-map#2]
Hi,

  Thanks for the great (suite of) hash libraries.  They cover a range of impressive performance characteristics!  I was wondering if it would be possible to provide some sort of serialization support so that a constructed hash could be serialized to disk and then deserialized in another application.  I tend to use hash tables a lot in such a scenario, where I build an index (usually over some genomic sequence) once, but then want to deserialize and use that index many times.

Thanks!
rob

**Comment by Tessil** [comment]
Hello,

It's something that I wanted to implement since some time but I have to check a bit what would be the best way to do it. I would like to be flexible enough so that the user can use `boost::serialization`, `cereal` or any other serialization library. If you have any suggestion regarding the serialization interface that could be used, feel free to comment. 

In the meantime you can iterate on the map and serialize each value, on deserialization you just insert the values back in an empty map (calling reserve beforehand). A more integrated serialization mechanism would make things  a bit easier and could use the internals of the hash map for a faster deserialization.

**Comment by rob-p** [comment]
Hi @Tessil,

  I currently use the [sparsepp](https://github.com/greg7mdp/sparsepp/) hash map, and end up using the `serialize` and `unserialize` functionality, as demonstrated [here](https://github.com/greg7mdp/sparsepp/blob/master/examples/serialize_large.cc).  Our projects also use cereal for other types of serialization, so support for that type of library would be fantastic.  One thing I'd like to avoid is saving key, value pairs to a file in a way that requires reading them all in before deserializing the map.  That is, you could put the key,value pairs in a vector and serialize them with cereal, but you really want to, as you say, reserve the proper size for the hash table and then populate it directly from file, not from an in-memory vector (this is particularly true given that the sparse-map library places a premium on the data structure size).  I don't have any particularly concrete suggestions apart from the following.  The design of sparsepp's serialization support works pretty well, as you can write one serializer that works for all POD types, and then you can specialize the serializer if you need to.  The other thing that would be awesome to have is support for serialization and deserialization via mmap, but I'm not sure how hard or easy that would be given the design of sparse-map.

**Comment by Tessil** [comment]
Hello,

I created a branch with some preliminary support for serialization. It's not complete yet (see [TODO list](https://github.com/Tessil/sparse-map/blob/e01e8d6771ed05a6a1c1f2648a641ebec3a490f9/include/tsl/sparse_hash.h#L1570)) and it needs more testing. 

The `serialization` and `deserialization` methods take respectively in arguments a `Serializer` and a `Deserializer`. They can be of any type, but they must have a `void serialize(const T& value)` method for `Serializer` and a `T deserialize()` method for `Deserializer`. They need to be able to work with the types `uint64_t`, `float`, `Key` and eventually `T` if a map is serialized.

The API seems quite flexible, but I still have to think about it a bit. Would it fit your needs?

Example with cereal:
```c++
#include <cereal/types/string.hpp>
#include <cereal/archives/binary.hpp>
#include <fstream> 
#include <tsl/sparse_set.h>
#include <tsl/sparse_map.h>

class Serializer {
public:    
    Serializer(const char* file): os(file), ar(os) {
    }
    
    template<typename T>
    void serialize(const T& v) {
        ar(v);
    }
    
private:    
    std::ofstream os;
    cereal::BinaryOutputArchive ar;
};

class Deserializer {
public:    
    Deserializer(const char* file): is(file), ar(is) {
    }
    
    template<typename T>
    T deserialize() {
        T v;
        ar(v);
        
        return v;
    }
    
private:  
    std::ifstream is;
    cereal::BinaryInputArchive ar;
};



int main() {
    tsl::sparse_map<std::string, std::size_t> map;
    tsl::sparse_map<std::string, std::size_t> map2;
    
    for(std::size_t i = 0; i < 1000; i++) {
        map.insert(std::make_pair("Key " + std::to_string(i), i));
    }
    
    
    {
        Serializer s("map.cereal");
        map.serialize(s);
    }
    
    {
        Deserializer deserializer("map.cereal");
        map2 = tsl::sparse_map<std::string, std::size_t>::deserialize(deserializer);
        assert(map == map2);
    }
    
        
    
    
    
    tsl::sparse_set<std::string> set;
    tsl::sparse_set<std::string> set2;
    
    for(std::size_t i = 0; i < 1000; i++) {
        set.insert("key " + std::to_string(i));
    }
    
    
    {
        Serializer ser("set.cereal");
        set.serialize(ser);
    }

    {
        Deserializer deserializer("set.cereal");
        set2 = tsl::sparse_set<std::string>::deserialize(deserializer);
        tsl_assert(set == set2);
    }
   
    return 0;
}
```

Here I lumped together the `std::ofstream` and `cereal::BinaryOutputArchive ` in `Serializer`, but the `std::ofstream` could be put somewhere else.

**Comment by Tessil** [comment]
Hi @rob-p 

Sorry for the long delay. I updated the branch a bit to add some tests, add support for serialization/deserialization between multiple platforms/libraries with a different hash for a type and changed a bit the interface. It should be production ready now, I just have to add some documentation before merging the branch to the master and add the support to the other projects in `tsl`. 

By default the deserialization method assumes that the hash on the platform where the serialization took place is not compatible with the one where the deserialization takes place. A `tsl::sparse_set<std::string>` will not look the same internally on Windows 32 bits with MSVC compared to Linux 64 bits with GCC. You can circumvent this assumption if you're sure that the hash is exactly the same by setting the `hash_compatible` parameter to true when you deserialize the set. On a `tsl::sparse_set<std::string>` with a `std::stringstream` buffer (so no I/O), I measured a gain of x2.

You can check an example of usage below. Warn me if it looks OK for your needs.

```c++
#include <cereal/archives/binary.hpp>
#include <cereal/types/string.hpp>
#include <fstream> 
#include <tsl/sparse_set.h>
#include <tsl/sparse_map.h>


// Inneficient hash different than std::hash<std::string>.
struct hash_str_size {
    std::size_t operator()(const std::string& s) const {
        return s.size();
    }
};
    
struct serializer {
    template<typename T, typename OutputStream>
    void operator()(const T& v, OutputStream& ostream) const {
        ostream(v);
    }    
    
    template<typename T, typename InputStream>
    T operator()(InputStream& istream) const {
        T v;
        istream(v);
        
        return v;
    }    
};




int main() {
    const std::size_t nb_elements = 1000;
    
    tsl::sparse_map<std::string, std::size_t> map;
    tsl::sparse_map<std::string, std::size_t> map2;
    
    for(std::size_t i = 0; i < nb_elements; i++) {
        map.insert(std::make_pair("Key " + std::to_string(i), i));
    }
    
    
    {
        std::ofstream os("map.cereal");
        cereal::BinaryOutputArchive ar(os);
        
        map.serialize(serializer(), ar);
//         map.serialize([](const auto& v, cereal::BinaryOutputArchive& ar) { ar(v); }, ar);
    }
    
    {
        const bool hash_compatible = true;
        
        std::ifstream is("map.cereal");
        cereal::BinaryInputArchive ar(is);
        
        map2 = tsl::sparse_map<std::string, std::size_t>::deserialize(serializer(), ar, 
                                                                      hash_compatible);
        // Require C++20 to use lambdas
//         map2 = tsl::sparse_map<std::string, std::size_t>::deserialize(
//                         []<typename T>(cereal::BinaryInputArchive& ar, hash_compatible) { 
//                             T v; ar(v); return v; 
//                         }, ar);
        assert(map == map2);
    }
    
        
    
    
    tsl::sparse_set<std::string> set;
    tsl::sparse_set<std::string, hash_str_size> set2;
    
    for(std::size_t i = 0; i < nb_elements; i++) {
        set.insert("key " + std::to_string(i));
    }
    
    
    std::stringstream buffer;
    {
        cereal::BinaryOutputArchive ar(buffer);
        
        set.serialize(serializer(), ar);
//         set.serialize([](const auto& v, cereal::BinaryOutputArchive& ar) { ar(v); }, ar);
    }

    
    {
        cereal::BinaryInputArchive ar(buffer);
        
        set2 = tsl::sparse_set<std::string, hash_str_size>::deserialize(serializer(), ar);
        // Require C++20 to use lambdas
//         set2 = tsl::sparse_set<std::string, hash_str_size>::deserialize(
//                                 []<typename T>(cereal::BinaryInputArchive& ar) { 
//                                     T v; ar(v); return v; 
//                                 }, ar);
        
        
        assert(set.size() == set2.size());
        for(const auto& value: set) {
            assert(set2.find(value) != set2.end());
        }
    }
    
    return 0;
}
```

**Comment by Tessil** [comment]
I merged the branch.

**Comment by rob-p** [comment]
Hi @Tessil,

  Sorry I dropped off the map on this.  I tested it out and it seems to work beautifully.  Thanks for this!
